import { AIModel } from '../types';

export const POLZA_MODELS: AIModel[] = [

    // ── Claude ──
    // Рассуждающие
    { id: 'anthropic/claude-3.7-sonnet:thinking', name: 'Anthropic: Claude 3.7 Sonnet (thinking)', category: 'Claude', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '251,79 ₽', completion: '1258,95 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    // Продвинутые
    { id: 'anthropic/claude-3.5-sonnet', name: 'Anthropic: Claude 3.5 Sonnet', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '503,58 ₽', completion: '2517,90 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'anthropic/claude-3.7-sonnet', name: 'Anthropic: Claude 3.7 Sonnet', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '251,79 ₽', completion: '1258,95 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'anthropic/claude-opus-4', name: 'Anthropic: Claude Opus 4', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '1258,95 ₽', completion: '6294,75 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'anthropic/claude-opus-4.1', name: 'Anthropic: Claude Opus 4.1', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '1258,95 ₽', completion: '6294,75 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'anthropic/claude-opus-4.5', name: 'Anthropic: Claude Opus 4.5', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '419,65 ₽', completion: '2098,25 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'anthropic/claude-sonnet-4', name: 'Anthropic: Claude Sonnet 4', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '251,79 ₽', completion: '1258,95 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'anthropic/claude-sonnet-4.5', name: 'Anthropic: Claude Sonnet 4.5', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '251,79 ₽', completion: '1258,95 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'anthropic/claude-sonnet-4.6', name: 'Anthropic: Claude Sonnet 4.6', category: 'Claude', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '251,79 ₽', completion: '1258,95 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    // Быстрые
    { id: 'anthropic/claude-3-haiku', name: 'Anthropic: Claude 3 Haiku', category: 'Claude', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '20,98 ₽', completion: '104,91 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'anthropic/claude-3.5-haiku', name: 'Anthropic: Claude 3.5 Haiku', category: 'Claude', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '67,14 ₽', completion: '335,72 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'anthropic/claude-haiku-4.5', name: 'Anthropic: Claude Haiku 4.5', category: 'Claude', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '83,93 ₽', completion: '419,65 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },

    // ── DeepSeek ──
    // Рассуждающие
    { id: 'deepseek/deepseek-r1', name: 'DeepSeek: R1', category: 'DeepSeek', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '124,64 ₽', completion: '498,54 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-r1-0528', name: 'DeepSeek: R1 0528', category: 'DeepSeek', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '46,16 ₽', completion: '180,45 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-r1-distill-llama-70b', name: 'DeepSeek: R1 Distill Llama 70B', category: 'DeepSeek', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '2,52 ₽', completion: '9,23 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-r1-distill-qwen-32b', name: 'DeepSeek: R1 Distill Qwen 32B', category: 'DeepSeek', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '41,97 ₽', completion: '409,58 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    // Продвинутые
    { id: 'deepseek/deepseek-chat', name: 'DeepSeek: DeepSeek V3', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '25,18 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-chat-v3-0324', name: 'DeepSeek: DeepSeek V3 0324', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '18,13 ₽', completion: '73,86 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-chat-v3.1', name: 'DeepSeek: DeepSeek V3.1', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '25,18 ₽', completion: '79,73 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-v3.1-terminus', name: 'DeepSeek: DeepSeek V3.1 Terminus', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '25,18 ₽', completion: '79,73 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-v3.1-terminus:exacto', name: 'DeepSeek: DeepSeek V3.1 Terminus (exacto)', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '17,63 ₽', completion: '67,14 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-v3.2', name: 'DeepSeek: DeepSeek V3.2', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '41,97 ₽', completion: '125,89 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-v3.2-exp', name: 'DeepSeek: DeepSeek V3.2 Exp', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '22,66 ₽', completion: '34,41 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'deepseek/deepseek-v3.2-speciale', name: 'DeepSeek: DeepSeek V3.2 Speciale', category: 'DeepSeek', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '33,57 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },

    // ── GLM ──
    // Продвинутые
    { id: 'z-ai/glm-4-32b', name: 'Z.AI: GLM 4 32B ', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '8,39 ₽', completion: '8,39 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'z-ai/glm-4.5', name: 'Z.AI: GLM 4.5', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '29,38 ₽', completion: '130,09 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'z-ai/glm-4.5-air', name: 'Z.AI: GLM 4.5 Air', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '12,59 ₽', completion: '50,36 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'z-ai/glm-4.5v', name: 'Z.AI: GLM 4.5V', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '50,36 ₽', completion: '151,07 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'z-ai/glm-4.6', name: 'Z.AI: GLM 4.6', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '36,93 ₽', completion: '146,04 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'z-ai/glm-4.6:exacto', name: 'Z.AI: GLM 4.6 (exacto)', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '36,93 ₽', completion: '147,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'z-ai/glm-4.6v', name: 'Z.AI: GLM 4.6V', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '25,18 ₽', completion: '75,54 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": true } },
    { id: 'z-ai/glm-4.7', name: 'Z.AI: GLM 4.7', category: 'GLM', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '43,64 ₽', completion: '146,88 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    // Быстрые
    { id: 'z-ai/glm-4.7-flash', name: 'Z.AI: GLM 4.7 Flash', category: 'GLM', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '5,88 ₽', completion: '33,57 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },

    // ── GPT ──
    // Рассуждающие
    { id: 'openai/o1', name: 'OpenAI: o1', category: 'GPT', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '1258,95 ₽', completion: '5035,80 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/o1-pro', name: 'OpenAI: o1-pro', category: 'GPT', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '12589,50 ₽', completion: '50358,00 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/o3', name: 'OpenAI: o3', category: 'GPT', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '167,86 ₽', completion: '671,44 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/o3-deep-research', name: 'OpenAI: o3 Deep Research', category: 'GPT', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '839,30 ₽', completion: '3357,20 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/o3-mini', name: 'OpenAI: o3 Mini', category: 'GPT', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '92,32 ₽', completion: '369,29 ₽' }, capabilities: { "text": true, "image": false, "file": true, "audio": false, "video": false } },
    { id: 'openai/o3-mini-high', name: 'OpenAI: o3 Mini High', category: 'GPT', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '92,32 ₽', completion: '369,29 ₽' }, capabilities: { "text": true, "image": false, "file": true, "audio": false, "video": false } },
    { id: 'openai/o3-pro', name: 'OpenAI: o3 Pro', category: 'GPT', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: true, pricing: { prompt: '1678,60 ₽', completion: '6714,40 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    // Продвинутые
    { id: 'openai/gpt-4.1', name: 'OpenAI: GPT-4.1', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '167,86 ₽', completion: '671,44 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-4o', name: 'OpenAI: GPT-4o', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '209,82 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-4o:extended', name: 'OpenAI: GPT-4o (extended)', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '503,58 ₽', completion: '1510,74 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-4o-search-preview', name: 'OpenAI: GPT-4o Search Preview', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: true, pricing: { prompt: '209,82 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'openai/gpt-5', name: 'OpenAI: GPT-5', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5-chat', name: 'OpenAI: GPT-5 Chat', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5-codex', name: 'OpenAI: GPT-5 Codex', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'openai/gpt-5-image', name: 'OpenAI: GPT-5 Image', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '0,00 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5-pro', name: 'OpenAI: GPT-5 Pro', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '1258,95 ₽', completion: '10071,60 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5.1', name: 'OpenAI: GPT-5.1', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5.1-chat', name: 'OpenAI: GPT-5.1 Chat', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5.1-codex', name: 'OpenAI: GPT-5.1-Codex', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'openai/gpt-5.1-codex-max', name: 'OpenAI: GPT-5.1-Codex-Max', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'openai/gpt-5.2', name: 'OpenAI: GPT-5.2', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '146,88 ₽', completion: '1175,02 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5.2-chat', name: 'OpenAI: GPT-5.2 Chat', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '146,88 ₽', completion: '1175,02 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5.2-pro', name: 'OpenAI: GPT-5.2 Pro', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '1762,53 ₽', completion: '14100,24 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5.2-codex', name: 'OpenAI: GPT-5.2-Codex', category: 'GPT', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '146,88 ₽', completion: '1175,02 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    // Быстрые
    { id: 'openai/gpt-4.1-mini', name: 'OpenAI: GPT-4.1 Mini', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '33,57 ₽', completion: '134,29 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-4.1-nano', name: 'OpenAI: GPT-4.1 Nano', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '8,39 ₽', completion: '33,57 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-4o-mini', name: 'OpenAI: GPT-4o-mini', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: true, pricing: { prompt: '12,59 ₽', completion: '50,36 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-4o-mini-search-preview', name: 'OpenAI: GPT-4o-mini Search Preview', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: true, pricing: { prompt: '12,59 ₽', completion: '50,36 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'openai/gpt-5-image-mini', name: 'OpenAI: GPT-5 Image Mini', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '209,82 ₽', completion: '167,86 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5-mini', name: 'OpenAI: GPT-5 Mini', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '20,98 ₽', completion: '167,86 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5-nano', name: 'OpenAI: GPT-5 Nano', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '4,20 ₽', completion: '33,57 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/gpt-5.1-codex-mini', name: 'OpenAI: GPT-5.1-Codex-Mini', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '20,98 ₽', completion: '167,86 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'openai/o4-mini', name: 'OpenAI: o4 Mini', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '92,32 ₽', completion: '369,29 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/o4-mini-deep-research', name: 'OpenAI: o4 Mini Deep Research', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '167,86 ₽', completion: '671,44 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },
    { id: 'openai/o4-mini-high', name: 'OpenAI: o4 Mini High', category: 'GPT', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '92,32 ₽', completion: '369,29 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": false, "video": false } },

    // ── Gemini ──
    // Продвинутые
    { id: 'google/gemma-2-27b-it', name: 'Google: Gemma 2 27B', category: 'Gemini', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '54,55 ₽', completion: '54,55 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'google/gemma-2-9b-it', name: 'Google: Gemma 2 9B', category: 'Gemini', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '2,52 ₽', completion: '7,55 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'google/gemma-3-12b-it', name: 'Google: Gemma 3 12B', category: 'Gemini', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '2,52 ₽', completion: '8,39 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'google/gemma-3-27b-it', name: 'Google: Gemma 3 27B', category: 'Gemini', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '3,36 ₽', completion: '12,59 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'google/gemma-3-4b-it', name: 'Google: Gemma 3 4B', category: 'Gemini', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '1,43 ₽', completion: '5,72 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'google/gemma-3n-e4b-it', name: 'Google: Gemma 3n 4B', category: 'Gemini', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '1,68 ₽', completion: '3,36 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    // Быстрые
    { id: 'google/gemini-2.0-flash-001', name: 'Google: Gemini 2.0 Flash', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '8,39 ₽', completion: '33,57 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-2.0-flash-lite-001', name: 'Google: Gemini 2.0 Flash Lite', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '6,29 ₽', completion: '25,18 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-2.5-flash', name: 'Google: Gemini 2.5 Flash', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '25,18 ₽', completion: '209,82 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-2.5-flash-image', name: 'Google: Gemini 2.5 Flash Image (Nano Banana)', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '0,00 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'google/gemini-2.5-flash-lite', name: 'Google: Gemini 2.5 Flash Lite', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '8,39 ₽', completion: '33,57 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-2.5-flash-lite-preview-09-2025', name: 'Google: Gemini 2.5 Flash Lite Preview 09-2025', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '8,39 ₽', completion: '33,57 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-2.5-pro-preview-05-06', name: 'Google: Gemini 2.5 Pro Preview 05-06', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-2.5-pro', name: 'Google: Gemini 2.5 Pro Preview 05-06', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-2.5-pro-preview', name: 'Google: Gemini 2.5 Pro Preview 06-05', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '104,91 ₽', completion: '839,30 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": false } },
    { id: 'google/gemini-3-flash-preview', name: 'Google: Gemini 3 Flash Preview', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '41,97 ₽', completion: '251,79 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-3-pro-preview', name: 'Google: Gemini 3 Pro Preview', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '167,86 ₽', completion: '1007,16 ₽' }, capabilities: { "text": true, "image": true, "file": true, "audio": true, "video": true } },
    { id: 'google/gemini-embedding-001', name: 'Google: Gemini Embedding 001', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '12,59 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'google/gemini-3.1-flash-image-preview', name: 'Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '20,98 ₽', completion: '125,89 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'google/gemini-3-pro-image-preview', name: 'Google: Nano Banana Pro (Gemini 3 Pro Image Preview)', category: 'Gemini', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '0,00 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },

    // ── Grok ──
    // Продвинутые
    { id: 'x-ai/grok-imagine-image', name: 'Grok Image', category: 'Grok', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '0,00 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'x-ai/grok-3-beta', name: 'xAI: Grok 3 Beta', category: 'Grok', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '419,65 ₽', completion: '2098,25 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'x-ai/grok-3', name: 'xAI: Grok 3 Beta', category: 'Grok', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '419,65 ₽', completion: '2098,25 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'x-ai/grok-4', name: 'xAI: Grok 4', category: 'Grok', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '251,79 ₽', completion: '1258,95 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    // Быстрые
    { id: 'x-ai/grok-3-mini-beta', name: 'xAI: Grok 3 Mini Beta', category: 'Grok', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '50,36 ₽', completion: '335,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'x-ai/grok-3-mini', name: 'xAI: Grok 3 Mini Beta', category: 'Grok', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '50,36 ₽', completion: '335,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'x-ai/grok-4-fast', name: 'xAI: Grok 4 Fast', category: 'Grok', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '16,79 ₽', completion: '41,97 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'x-ai/grok-4.1-fast', name: 'xAI: Grok 4.1 Fast', category: 'Grok', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '16,79 ₽', completion: '41,97 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'x-ai/grok-code-fast-1', name: 'xAI: Grok Code Fast 1', category: 'Grok', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '16,79 ₽', completion: '125,89 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },

    // ── Qwen ──
    // Рассуждающие
    { id: 'qwen/qwen-plus-2025-07-28:thinking', name: 'Qwen: Qwen Plus 0728 (thinking)', category: 'Qwen', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: false, pricing: { prompt: '33,57 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-235b-a22b-thinking-2507', name: 'Qwen: Qwen3 235B A22B Thinking 2507', category: 'Qwen', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: false, pricing: { prompt: '23,50 ₽', completion: '193,04 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-30b-a3b-thinking-2507', name: 'Qwen: Qwen3 30B A3B Thinking 2507', category: 'Qwen', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: false, pricing: { prompt: '7,55 ₽', completion: '25,18 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-next-80b-a3b-thinking', name: 'Qwen: Qwen3 Next 80B A3B Thinking', category: 'Qwen', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: false, pricing: { prompt: '12,59 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-vl-235b-a22b-thinking', name: 'Qwen: Qwen3 VL 235B A22B Thinking', category: 'Qwen', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: false, pricing: { prompt: '82,25 ₽', completion: '331,52 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-vl-30b-a3b-thinking', name: 'Qwen: Qwen3 VL 30B A3B Thinking', category: 'Qwen', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: false, pricing: { prompt: '16,79 ₽', completion: '83,93 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-vl-8b-thinking', name: 'Qwen: Qwen3 VL 8B Thinking', category: 'Qwen', subCategory: 'thinking', desc: 'Модель с рассуждениями для задач высокой сложности.', isActual: false, pricing: { prompt: '9,82 ₽', completion: '114,56 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    // Продвинутые
    { id: 'qwen/image', name: 'Qwen Image', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '0,00 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-2.5-72b-instruct', name: 'Qwen2.5 72B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '25,18 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-2.5-coder-32b-instruct', name: 'Qwen2.5 Coder 32B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '2,52 ₽', completion: '9,23 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwq-32b', name: 'Qwen: QwQ 32B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '20,98 ₽', completion: '20,98 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-plus-2025-07-28', name: 'Qwen: Qwen Plus 0728', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '33,57 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-vl-max', name: 'Qwen: Qwen VL Max', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '67,14 ₽', completion: '268,58 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-vl-plus', name: 'Qwen: Qwen VL Plus', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '17,63 ₽', completion: '52,88 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-max', name: 'Qwen: Qwen-Max ', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '134,29 ₽', completion: '537,15 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-plus', name: 'Qwen: Qwen-Plus', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '33,57 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-turbo', name: 'Qwen: Qwen-Turbo', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '4,20 ₽', completion: '16,79 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-2.5-7b-instruct', name: 'Qwen: Qwen2.5 7B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '3,36 ₽', completion: '8,39 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen2.5-coder-7b-instruct', name: 'Qwen: Qwen2.5 Coder 7B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '2,52 ₽', completion: '7,55 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen2.5-vl-32b-instruct', name: 'Qwen: Qwen2.5 VL 32B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '4,20 ₽', completion: '18,46 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen2.5-vl-72b-instruct', name: 'Qwen: Qwen2.5 VL 72B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '12,59 ₽', completion: '50,36 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen-2.5-vl-7b-instruct', name: 'Qwen: Qwen2.5-VL 7B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '16,79 ₽', completion: '16,79 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-14b', name: 'Qwen: Qwen3 14B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '4,20 ₽', completion: '18,46 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-235b-a22b', name: 'Qwen: Qwen3 235B A22B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '25,18 ₽', completion: '100,72 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-235b-a22b-2507', name: 'Qwen: Qwen3 235B A22B Instruct 2507', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '12,55 ₽', completion: '50,19 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-30b-a3b', name: 'Qwen: Qwen3 30B A3B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '5,04 ₽', completion: '18,46 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-30b-a3b-instruct-2507', name: 'Qwen: Qwen3 30B A3B Instruct 2507', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '10,91 ₽', completion: '43,64 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-32b', name: 'Qwen: Qwen3 32B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '6,71 ₽', completion: '23,50 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-8b', name: 'Qwen: Qwen3 8B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '4,20 ₽', completion: '33,57 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-coder-30b-a3b-instruct', name: 'Qwen: Qwen3 Coder 30B A3B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '24,55 ₽', completion: '122,75 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-coder', name: 'Qwen: Qwen3 Coder 480B A35B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '81,83 ₽', completion: '409,16 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-coder:exacto', name: 'Qwen: Qwen3 Coder 480B A35B (exacto)', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '31,89 ₽', completion: '128,41 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-coder-plus', name: 'Qwen: Qwen3 Coder Plus', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '83,93 ₽', completion: '419,65 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-embedding-4b', name: 'Qwen: Qwen3 Embedding 4B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '1,68 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-embedding-8b', name: 'Qwen: Qwen3 Embedding 8B', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '4,20 ₽', completion: '0,00 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-max', name: 'Qwen: Qwen3 Max', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '100,72 ₽', completion: '503,58 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-next-80b-a3b-instruct', name: 'Qwen: Qwen3 Next 80B A3B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '8,18 ₽', completion: '65,47 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-vl-235b-a22b-instruct', name: 'Qwen: Qwen3 VL 235B A22B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '21,82 ₽', completion: '87,29 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-vl-30b-a3b-instruct', name: 'Qwen: Qwen3 VL 30B A3B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '12,59 ₽', completion: '50,36 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-vl-32b-instruct', name: 'Qwen: Qwen3 VL 32B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '41,97 ₽', completion: '125,89 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    { id: 'qwen/qwen3-vl-8b-instruct', name: 'Qwen: Qwen3 VL 8B Instruct', category: 'Qwen', subCategory: 'advanced', desc: 'Продвинутая модель для больших запросов и ответов.', isActual: false, pricing: { prompt: '20,98 ₽', completion: '62,95 ₽' }, capabilities: { "text": true, "image": true, "file": false, "audio": false, "video": false } },
    // Быстрые
    { id: 'qwen/qwen3-coder-flash', name: 'Qwen: Qwen3 Coder Flash', category: 'Qwen', subCategory: 'fast', desc: 'Быстрая модель для простых и частых задач.', isActual: false, pricing: { prompt: '25,18 ₽', completion: '125,89 ₽' }, capabilities: { "text": true, "image": false, "file": false, "audio": false, "video": false } },
];
